### ISSUE TITLE
Share an exception

### ISSUE THREAD

**Issue by JamieRushton** [exceptionless/Exceptionless#118]
Being able to share an exception with somebody outside of my organisation who may not have access to our Exceptionless account - I found a scenario today where a share option would have been awesome!

In an ideal world you'd forward a URL over to the user and have be able to look over the exception in all it's glorious icky detail (maybe even make comments?)

**Comment by niemyjski** [comment]
I've been thinking this over and I almost think we'd need to have to tag an event as public via some kind of share functionality.
1. This could tag the event as public
2. Create a public url /events/id/public for users to share that is a limited subset of functionality.

@ejsmith : If we don't tag an event, we'd have to figure something out because a user might be able to guess semi sequential event id's.

**Comment by niemyjski** [comment]
Merged into https://github.com/exceptionless/Exceptionless/issues/152
