### ISSUE TITLE
Version completion of Mark Fixed

### ISSUE THREAD

**Issue by PhyxionNL** [exceptionless/Exceptionless#1288]
If you type 1.0, it's completed to 1.0.0 automatically. But this is not a good completion if you want to write 1.0.1. The completion of 1.0 to 1.0.0 should only occur after pressing **Mark Fixed** button.

**Comment by niemyjski** [comment]
I've resolved this issue and a different bug where the version can be lost in the latest nightly. We now wait a full second before applying any changes. If you click submit super fast, you may need to click it again as validation will fail and then it will be converted. We can work towards improving this more but it's way better than what it was (just getting lost)

For context, the api endpoint accepts any string and will try to parse it to semver. I wanted this ui because it's the first touch point around how our version system works. I wanted to let the user what we would treat their versions behind the scenes.
