### ISSUE TITLE
Per request ExceptionlessClient settings

### ISSUE THREAD

**Issue by Kordonme** [exceptionless/Exceptionless#134]
Hello guys,

We host multiple Exceptionless projects in a single MVC project. How would we go around implementing this?

We could update Exceptionless.ExceptionlessClient.Default.Configuration.ApiKey on each request, but that doesn't seem very thread-safe.

Could I hook in right before the exception/event is sent and grab the API key from our own settings?

Thanks in advance,
Mark

**Comment by niemyjski** [comment]
Hey,

You would need to new up multiple instances of the client and store them someplace (static). The ApiKey property is locked and can't be changed once a submission occurs, this is because the queue uses the api key to function properly.

You could do some other things but I wouldn't recommend it, like implement your own ISubmissionClient and do what you say, but you have no clue what api key you should use for a specific set of events (bulk).

**Comment by niemyjski** [comment]
How is your setup for multiple clients inside of the same mvc app?

**Comment by Kordonme** [comment]
I actually think I got it working. I found the SubmittingEvent where I was able to change the Api key. I'm not sure if that's the correct way of doing it. 

We agreed to settle on this and not use too many resources on this issue - so we went with one Exceptionless project = one of our MVC applications.

Thanks for the help though :)

**Comment by niemyjski** [comment]
Yeah, that is what we do with our projects (one mvc app = one exceptionless project).  Also, I wouldn't set the api key in the SubmittingEvent, as the first time would work but the second time will fail if they key is different. Are you trying to read it from a database? In the future, if you get more time, please contact us and I can work with you on setting this up.
