### ISSUE TITLE
Missing system dashboard?

### ISSUE THREAD

**Issue by Kordonme** [exceptionless/Exceptionless#149]
I've always been wondering what this dashboard is for?

http://i.imgur.com/vpYGIXJ.png

**Comment by niemyjski** [comment]
in 1.x we had a complete admin ui for us to managing organizations like seeing what ones were suspended, reports and doing all this other stuff. We didn't have time to do that since we completely rewrote in angular so it's sitting there if you are a global admin. We hope to fill it out one of these days. We should probably add some text to that page. Would you mind doing a pull request for that? :+1:

**Comment by niemyjski** [comment]
I've added some text and removed this menu entry for now.

**Comment by Kordonme** [comment]
Thanks for the answer, was exactly what I expected :+1:
