### ISSUE TITLE
Any plans to move to asp.net Core?

### ISSUE THREAD

**Issue by AnderssonPeter** [exceptionless/Exceptionless#233]
Are there any plans to move to asp.net core?

**Comment by niemyjski** [comment]
Were adding support for the clients right now (https://github.com/exceptionless/Exceptionless.Net/issues/28), I've already ported the core library to .net standard 1.2 and should have a beta here within the next week. We won't be upgrading the server to asp.net core until the dest settles post rtm (they are about to announce a massive list of changes coming to asp.net core + project system that will be coming pre/post rtm)

I'm going to close this as we have an issue tracking asp.net core support :)

**Comment by niemyjski** [comment]
​Hey, I wanted to let you know that we have a nightly build which is stable and will become a beta release. It's on nuget as a prerelease v4 build. It's a major version because we got rid of the portable package and merged everything in to the Exceptionless package and made it pcl + .net standard.  Please feel free to update your nuget packages to this release and let us know about any issues.  If you want just core clr support install the Exceptionless package, if you want asp.net core support please install the Exceptionless.AspNetCore package :) and follow the readme. Please let us know if you have any feedback or run into any issues.

**Comment by AnderssonPeter** [comment]
Thanks @niemyjski but I'm sorry to say until the host part is ported to asp.net Core its unlikely that I can use it in my project.
Otherwise this logmanager seems like a great product!

**Comment by niemyjski** [comment]
We're still waiting on core dependencies to be updated. To core clr

**Comment by AnderssonPeter** [comment]
Ok @niemyjski  thanks for the update :).

**Comment by AnderssonPeter** [comment]
@niemyjski is there any issue for this, that contains a list of all dependencies and which are ported to core clr?

**Comment by niemyjski** [comment]
There currently is no issue tracking this but it is something we are actively working on and will start investigating (open an issue for) post rtm. Off the top of my head we'll have to port to elastic search 5.1 (not yet released), foundatio, oauth2 before we can upgrade to core clr and that is the biggest blocker.

**Comment by yetanotherchris** [comment]
Signalr isn't getting .net core'd until April 2017 according to the roadmap, so presumably it won't be before then?

**Comment by niemyjski** [comment]
We are about a little less than half way through migrating to elastic search 5 which is the biggest road block to asp.net core. We don't have a solid date but it will be after SignalR ships as we need it (or something that does web sockets really well. I'm fine with waiting at this point because every other day Microsoft changes direction on tooling (which won't be out until VS2017 is released) and .NET Core 2.0 which will have the full api set.

I think when we do this, we are going to dockerize everything so it's very easy to run exceptionless.
