### ISSUE TITLE
Update self hosted docs

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#252]

**Comment by SNajm** [comment]
the latest version of Elastic Search is at 5 now.

**Comment by ejsmith** [comment]
We are in the (long and painful) process of migrating our app to Elasticsearch 5. It has been a lot of work because they made a lot of breaking changes and removed features that we were using, but we are getting really close. We also took the opportunity to refactor our repositories and add a bunch of really useful features that will help us going forward.

**Comment by SNajm** [comment]
I understand that... but my reference was that your documentation needs to be updated cause it is a bit confusing.
Your documentation mentions that latest as being 2.x

**Comment by niemyjski** [comment]
Would you mind updating the wiki to mention 5.x instead

**Comment by SNajm** [comment]
I could if you don't mind me doing that.

**Comment by niemyjski** [comment]
The docs have been updated
