### ISSUE TITLE
How to add screenshoot

### ISSUE THREAD

**Issue by emejibka** [exceptionless/Exceptionless#255]
Hello, everyone ;)
I want to attach a screenshot of my app when i send exception to exceptionless. How i can do this?

**Comment by niemyjski** [comment]
We don't support this out of the box due to security reasons and currently have no plans to support this out of the box (this could change if the reasons below change + there is greater demand for this).

We take security very seriously but also feel that sensitive data shouldn't be sent when possible. It's impossible to explicitly capture a screenshot of your running app without the possibility of also capturing sensitive data from other windows or your own app which may contain banking, medical and other types of sensitive info.  I'd be more than happy to show you how you could write a plugin to capture a screenshot and save it to some kind of external service using plugins https://github.com/exceptionless/Exceptionless.Net/wiki/Adding-Plugins

Please let me know if you have any questions or feedback.

**Comment by niemyjski** [comment]
To iterate, you'd need to create a plugin as shown above, take a screenshot and then upload it or store it on some service using .net api's inside of the plugin :)
