### ISSUE TITLE
Integration with ASP.NET

### ISSUE THREAD

**Issue by davidkeaveny** [exceptionless/Exceptionless#264]
I've installed Exceptionless and Exceptionless.Web (both v4.0.1924) in an application that uses a combination of ASP.NET WebForms and MVC; the Exceptionless module was added to my web.config, and my application start-up code configures the default client, including turning on reference Ids and setting the current application version number. Everything works nicely, and exceptions appear in the portal.

However, I would now like to expose the Reference Ids on an error handling page. I tried adding a call to `ExceptionlessClient.Default.GetLastReferenceId()` in my custom error page, but it comes up empty. I'm wondering if that is because it is being set in the HTTP module, and maybe I should be using the `Application_Error` handler in global.asax instead?

While I'm at it, this approach with the HTTP module seems to have broken our previous error reporting mechanism, based on Microsoft's Enterprise Library v5 Exception Logging code - the last line of our Application_Error handler throws it to log4net to log to disk and to EntLib to send error emails - log4net is working but EntLib no longer works.

**Comment by niemyjski** [comment]
If you are using WebForms and MVC, I'd bring in the Exceptionless.Mvc package instead of the .Web package as it has an extra error handler and could be The reason you are missing the last reference id. Can you try this and let me know. If you still aren't seeing the reference id, could you please create a small sample that can reproduce it and I'll take a look at this under the debugger.  

We rethhrow the error and shouldn't be interfering with any of the workflows (we simply just log it). If you remove exceptionless does that start working again?

I'm going to close this, if you have a follow up or are still seeing this issue let me know and I'll reopen it.

**Comment by kiquenet** [comment]
have you Code , startup and application_error? and loggingconfiguration for
ent lib?

**Comment by niemyjski** [comment]
We just wire up to the asp.net exception handlers and life cycle events (Application Error and more). We don't have anything specific for enterprise library.  Would you mind looking into this further for us?

**Comment by niemyjski** [comment]
Were you able to figure out what was going on with ent lib?

**Comment by davidkeaveny** [comment]
I'd forgotten how much of a pain EntLib is to configure. I wasn't able to reproduce with a clean solution, and TBH, I would rather see the back of it anyway. Exceptionless is making EntLib's exception handling block fairly superfluous anyway when it comes to unhandled errors, so I'm not inclined to put any more time into investigating further.
