### ISSUE TITLE
Cannot support redis Queue with server load balance environment.

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless#326]
Since the high performance requirements, we are trying to deploy exceptionless in the load balance environment. 
After investigation, we intended to make use of different `AppScope` in settings for every exceptionless servers. But this configuration value affects the data storage in elasticsearch, so we got the absolutely separated data space for every exceptionless server.
Then we removed the `AppScope` in configuration, but there are lots of errors in the EventPostJob. 
After analyse the source code, we think the the scenario should be like the following diagram:
![_15094373592081](https://user-images.githubusercontent.com/2819989/32214756-e010d96a-be5a-11e7-9ce0-06efb7482f23.png)
step 1. The server A enqueued the event A1
step 2. The server B enqueued the event B1
step 3. The EventPostJob on the server B dequeued the event reference A1 in the head of Redis Queue.
For the last step on the server B, there will be none of the event file can be found for the event reference A1.

**Comment by niemyjski** [comment]
Yes, this could absolutely happen because we process the first enqueued item. However if you are using the same queue instance + storage and you enqueue a then b, a should always be processed before b.

**Comment by niemyjski** [comment]
Can you please expand on what your PR adds?

**Comment by edwardmeng** [comment]
Add `QueueScope` in settings used to generate queue name in redis or windows azure. For exceptionless servers in the load balance environment, avoid the absolutely separated data storage in elasticsearch when using `AppScope`, and avoid errors of chaos event reference among servers by using the default generated queue name without server specified prefix.

**Comment by niemyjski** [comment]
I'm not completely sure I agree with this because the app scope is for scoping different environments and now I have to set two different properties to get the same thing. We load balance everything and we have yet to run into any issues. I think the proper way to spread out the load on massive environments would be to create pods and shard on organizations. Please let me know what I'm missing...

@ejsmith input?

**Comment by edwardmeng** [comment]
According to my understanding, you have created several absolutely separated app scopes, and leads the different organizations to the allocated server in advance through the nginx or other load-balancer. 
Maybe the deployment diagram looks like this:
![_15095868484142](https://user-images.githubusercontent.com/2819989/32305701-f4f59aac-bfb1-11e7-9c94-e207fc94c146.png)

I think in this scenario, the app scope is useless, since we can deploy different elasticsearch services for every exceptionless server. Maybe the deployment diagram looks like this:
![_15095871304024](https://user-images.githubusercontent.com/2819989/32305824-97213fca-bfb2-11e7-8a2d-4e1ed77772a0.png)

But we have only one organization and massive events(more than billion totally, more than 10 thousand per second). So we cannot deployed with your solution. In our deployment, every exceptionless servers have to be provided for same organization same project, so the events they received have to be stored in the same elasticsearch cluster same app scope. Here is our deployment diagram:
![_15095877412252](https://user-images.githubusercontent.com/2819989/32306033-1377fd24-bfb4-11e7-99d2-4da04e7d87e8.png)

So the `QueueScope` and `AppScope` should be standalone configured, and my changes are based on our solution. When the `QueueScope` is not specified, its value should be same to `AppScope` to compatible with your solution.

**Comment by ejsmith** [comment]
AppScope is for segregating data so that you can have multiple isolated instances of Exceptionless sharing the same Elasticsearch, Redis and queue resources.

If you are looking to handle high volumes of data, then The whole system is designed to scale out. Add more nodes to your ES cluster, Redis cluster, more job processor instances etc. Soon we will have the whole system dockerized and then it will be a lot easier to scale it all out. Is that answering your question?

BTW, nice diagrams! What did you use to make those?

**Comment by niemyjski** [comment]
Also on a side note, I'm getting real close to having asp.net core support and running all the jobs on .net core (testing and testing.... getting close to using to QA). We've also done some pretty awesome perf work (and lots more todo) thanks to @redknightlois Would love to hear how the next version preforms on your cluster :)

**Comment by edwardmeng** [comment]
@ejsmith as you said, we have deployed several nodes of elasticsearch cluster, redis cluster, and there are more than ten job processors. We have noticed that from the events submitted to exceptionless server to stored in elasticsearch, the time duration will be more than 2 hours in the rush hours, which is not acceptable. After analyzing logs and performance monitors, we found the bottle neck is the performance of hard disk on exceptionless server, although our servers used SSD.
In order to improve performance further more, we have to consider the load balance solution. After trying that, the only stumbling block is the redis queue cannot be scoped.

**Comment by ejsmith** [comment]
That’s interesting. What kind of load are we talking about?

We obviously have a pretty good sized amount of traffic on our hosted instance with all our customers and we monitor things like queue time and we are able to keep the queue times within seconds.

If you are wanting one org and one project then you definitely need to scale out and we need to figure out what is going on with your setup. Where are you seeing the disk usage being high? On the ES nodes?

**Comment by edwardmeng** [comment]
@ejsmith Could you please tell me about the sized amount of traffic on your hosted instance, and what you have done to keep the queue time within seconds? Maybe our prerequisites are different, so the deployment strategy are different too.
Our performance bottle neck is the **hard disk and CPU on exceptionless server, not on the ES nodes**. Please refer to my previous comments. Since we have deployed zabbix to monitor every server any aspect performance issues. Please refer to the following table

Server | CPU Usage | Memory Usage | Disk Time
--------|-------------|------------------|--------------
Exceptionless   | 92% | 77.41% | 4s
Redis                |   8% | 3.02% | 0.2s
ElasticSearch    | 38% | 44.56% | 1.3s

We have only one org, so we have to the unique es cluster, the unique `AppScope`. The only way for us is to load balance the exceptionless server **with different `QueueScope` but not `AppScope`**

**Comment by niemyjski** [comment]
We use high performance blob storage in azure and stream our writes there (more could be done as I'm sure there are some places were we might not be streaming it and taking a buffering hit on the app server...  We also use premium redis and premium vms for elastic. Ideally when we rebuild with k8s we will go with nvme backed storage. We switched from redis queues to azure storage queues so we could trigger scale outs. But we are going to be looking into switching back to redis for queues or something else that we can host inside of k8s.  We've done a ton of work in the nightly to the redis queues and job workers.  In my local benchmark there was 20-40% improvement in some areas to queue jobs and processing and more can be done to prefetch io bound tasks. So it might be worth looking into if all that cpu usage is for writing to disk. Are you writing to a NAS or purely local storage? There might be a lot of CPU / IO Contention on the web boxes.

**Comment by edwardmeng** [comment]
@niemyjski In China the blob storage in azure is more expensive than aliyun and the performance is not as well as excepted since the network causes. So we have to write event files in the local storage on SSD(The NAS has not been in view), and the event files cannot be shared among exceptionless servers. It means the queue must be absolutely separated for every exceptionless server to avoid the issue I have mentioned, no matter redis queue, windows azure queue or other kind queues.
If we use the NAS or blob storage in cloud, the throughput of `EventController` will be not enough for our applications. Then there will be too much event files accumulated and abandoned, which is not acceptable. Once a time, there are more than 100G event files in some application servers.
Our core business run on SaaS mode, there are more hundred application servers has been deployed. And for every application server, there are three websites, ten application services. In our report, there are more than hundred events produced per second. So totally, there will be 100*6*100 = 60,000 events per second will be submitted to the exceptionless cluster when we declare the logging solution and decide to deploy for every customers.
The in-process jobs have been disabled in exceptionless website, instead we have deployed the jobs as windows service, especially there are 10 services for `EventPostJob` every exceptionless server. Now there are at least 5,000 events can be posted to elasticsearch per second per server, so we have to deploy at least 12 exceptionless servers. But the concurrency issues should be fixed.

**Comment by niemyjski** [comment]
I think the main reason you can't scale out very well is that your using local storage for the queue instead of shared storage where the writes can be distributed. We use premium blob storage for better performance. (We are wanting to make exceptionless run on k8's and apart of that is possibly running storage in minio (possibly)). What issues are you seeing with the NAS (even if it's all ssd backed)? I think we need to take a look and ensure we are streaming correctly from the Event Controller and preloading io tasks in the job. This would reduce a lot of the latencies.

**Comment by edwardmeng** [comment]
@niemyjski We are trying to NAS storage today, but I don't think the performance will be better than local storage in every exceptionless servers.
On the other side, the exceptionless should support distributed local storage mode in my mind. Since it's the simplest and fast enough deployment strategy.

**Comment by ejsmith** [comment]
@edwardmeng the problem isn't storage performance. The problem is that in order to scale out, you have to use shared storage. Each worker (web and job) needs to be able to read and write from shared storage to process event queue items that are persisted to disk. I'm not even sure how your setup is working now if you have multiple instances of the job and api running on different machines. The api can easily write event queue entries to local storage, but the job processors just dequeue the next item from the queue without any knowledge of where that item is stored.

You may be able to use something like https://www.minio.io/ and run that on each node. We have a Foundatio S3 storage provider. I don't think we currently have the ability to configure that in Exceptionless, but that would be trivial to add support for.

I guess another option is maybe what you are trying to get at which is each node would have its own private queue and you would run both the api and job on the node and so that the job only gets events that were received and stored on the same node. You would have to put a round robin load balancer in front of the nodes to try and evenly distribute the events coming in, but even that wouldn't make it equal since some posts can be single events and some can be 1000 events in a batch. It seems like kind of a hokey way to scale out, but I guess it would work.

**Comment by edwardmeng** [comment]
@ejsmith Yes, we are exactly deployed as you said, so we wanna private queue for each exceptionless node. So the changes in this pr is just for this purpose.

**Comment by ejsmith** [comment]
Ok, I think we are finally on the same page. :) So you are using your changes now? If so, how is that working for you?

**Comment by ejsmith** [comment]
I'm thinking we should default the QueueScope to the machine name if we are using in memory queues.

**Comment by niemyjski** [comment]
I think that if we did queue scopes on node name, we should make this append prefix only so existing scopes just works. Currently I don’t like that queue scopes change existing scope behaviors. Seems like this would be useful in your case which I don’t think is very normal... it’s almost like you have pods but the same elastic instance... what if you just had isolated pods connected via tribe nodes?

**Comment by niemyjski** [comment]
@ejamith how would that help with in memory queues ?

**Comment by edwardmeng** [comment]
@ejsmith Yes, we are using the changes and it works very well except the issue https://github.com/exceptionless/Exceptionless/issues/328. 
@niemyjski There is wechat group for exceptionless communication in China, and as I know almost 99%  of them have been deployed with the local storage, since the solution is simple, requires less servers, and has enough scale out possibility for medium organizations.
We have only one product for many SaaS customers, and cannot provide tribe nodes for the instances. Since that will lead unnecessary management and maintain complexity. e.g. the feature usage and exceptions should be collected and analyzed globally to help us improve the product quality.

**Comment by ejsmith** [comment]
Hmm... yeah, wasn't thinking. It wouldn't help in memory queues. @edwardmeng have you tried just running several instances using in memory queues and running the event job in process?

I am good with making this change, but I'm trying to think if there is maybe a better name for the option because I'm worried about it being confusing with AppScope. Also, I guess we can check to see if you are not using in memory queues and you are using folder based storage then we could enable this option. So if you turn Redis on, but don't use Azure storage then this option would default to the computer name and it should work out of the box.

**Comment by edwardmeng** [comment]
@ejsmith I think the option should default to computer name maybe for in memory queues, but not for all scenarios. Such as when using Redis queue and NAS or Azure storage, the default value should be same as `AppScope`.
Another scenario, when using Redis queue and local storage, if the option default to computer name, and there are some computer with the exactly same name, the event files will be chaos too.
note: For some data center, the computers are installed with the same name by default, only if you ask them to change the computer name or join computers in the same domain.

**Comment by niemyjski** [comment]
@edwardmeng I don't think any changes are needed for AppScope. I think we should just default QueueScope to null and never set it or even put it in the web.config as a known key. Then just preappend that value that's manually set to the queues. That way we get auto environments as well as queue scoping if it works.

**Comment by niemyjski** [comment]
@edwardmeng any way to get invited to the WeChat group? We'd love to have them on our (http://slack.exceptionless.com) too :)

**Comment by ejsmith** [comment]
I think he is right. We just default it to the AppScope value and use it instead of AppScope in the queue factory which is exactly what he is already doing. Let’s accept this PR as is @niemyjski. Thank you @edwardmeng and sorry it took so long to talk it through.
