### ISSUE TITLE
Can't able to log error from Console application

### ISSUE THREAD

**Issue by LTAravindh** [exceptionless/Exceptionless#334]
Hi, 

 I have used Self-hosted Exceptionless to log error. It will be working fine in MVC web applications but won't work in console application.

Please find my code:
```

  class Program
    {
        static void Main(string[] args)
        {
            ExceptionlessClient ec = ExceptionlessClient.Default;
            ec.Configuration.ApiKey = "my key";
            ec.Configuration.ServerUrl = "my hosted link";
            test();
        }

        public static void test()
        {


            ExceptionlessClient.Default.Configuration.UseFileLogger("C:\\exceptionless.log");
            try
            {
                throw new AbandonedMutexException();
            }
            catch (Exception e)
            {
                new WebErrorTracker(e);
            }
        }
```

App.config file codes.
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="exceptionless" type="Exceptionless.ExceptionlessSection, Exceptionless" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
  <appSettings>
  </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    
    </assemblyBinding>
  </runtime>
  <exceptionless apiKey="my key" serverUrl="my hosted site" enableLogging="true" logPath="C:\exceptionless.log" />
</configuration>
```

What I'm missing here?

Thanks,
Aravindh LT

**Comment by niemyjski** [comment]
You are missing the call to start errors tracking with the call to `Exceptionless.ExceptionlessClient.Default.Startup()`. This will only catch unhandled errors, you'll need to submit this error inside of your WebErrorTracker by submitting it as shown here: https://github.com/exceptionless/Exceptionless.Net/wiki/Sending-Events

Also, since this is a test console app, it could exit before the queue is processed: https://github.com/exceptionless/Exceptionless.Net/wiki/Troubleshooting#ensure-the-queue-has-time-to-process

I'd also make sure that you turn off both `enableLogging="true" logPath="C:\exceptionless.log"` and `ExceptionlessClient.Default.Configuration.UseFileLogger("C:\\exceptionless.log");` before deploying your app or put them behind a compiler directive as those are for diagnostic purposes :). Please let us know if you have any questions or need further assistance and we'll reopen the issue.
