### ISSUE TITLE
Create My Account Failed

### ISSUE THREAD

**Issue by chenp1204** [exceptionless/Exceptionless#340]
Hi，
elasticsearch version: 5.6.5
exceptionless version: 4.1.2861

When i change the version of Elasticsearch to 5.6.5 and use your config file elasticsearch.yml replace Elasticsearch's config，the login page of exceptionless is login successed，but when create my account is failed.

# the following is the request infomation：
## General:
Request URL:http://127.0.0.1:9005/api/v2/auth/signup
Request Method:POST
Status Code:400 Bad Request
Remote Address:127.0.0.1:9005
Referrer Policy:no-referrer-when-downgrade

# Request Payload
{"password":"111111","email":"pengc2834@kotei-info.com","name":"pengc"}

# Response
{
  "Message": "An error occurred."
}

# This is the information of Elasticsearch 5.6.5
{
  "name" : "cmzbtBD",
  "cluster_name" : "exceptionless",
  "cluster_uuid" : "9KjV5FTDTMqNJDz_WGI2Lw",
  "version" : {
    "number" : "5.6.5",
    "build_hash" : "6a37571",
    "build_date" : "2017-12-04T07:50:10.466Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by niemyjski** [comment]
@chenp1204 If I had to guess it's because of the in memory cache wasn't cleared when you upgraded elasticsearch. Does recycling the iis app fix this issue? Can you also enable logging or look at the event logs for this error (https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting). My apologies for all the issues you are running into.

**Comment by niemyjski** [comment]
Can you please let me know if you are still running into this behavior after following the troubleshooting guide.
