### ISSUE TITLE
Easy way to update project bot definitions

### ISSUE THREAD

**Issue by hmvs** [exceptionless/Exceptionless#38]
Please add to Known Bots list useragent : "ContextAd Bot 1.0"

**Comment by niemyjski** [comment]
In 2.0, you can add a list of bot definitions to your project configuration. Do you think this should also be organization wide or maybe even system wide?

https://github.com/exceptionless/Exceptionless/blob/5fc53f1acd2e3573081148ff77d6d824b720a2ee/Source/Core/Plugins/EventProcessor/Default/40_RequestInfoPlugin.cs#L52-L56

**Comment by niemyjski** [comment]
Do you think we should have some kind of bot database that we read these from? Since importing the data into ElasticSearch, I can tell you that there are thousands of variations of bot user agents. I've been wanting to export these and submit them to the UA Parser project (which we use to detect bots).

**Comment by niemyjski** [comment]
I guess one thing we could have is a job that runs and does a ElasticSearch Query to get all of the unique user agents for the day and we filter out the known ones?? Thoughts?

**Comment by fbm-static** [comment]
I don't know about you, but I know about me. :smirk_cat:

**Comment by niemyjski** [comment]
@fbm-static were you able to get this working?

**Comment by niemyjski** [comment]
We now support this via the manage project page and added a default list of bots that covers a very large percentage of bots. The clients now automatically discard events from bots :)
