### ISSUE TITLE
ElasticSearch indices

### ISSUE THREAD

**Issue by qwertio** [exceptionless/Exceptionless#407]
When resetting project data, should Exceptionless remove the event-* indices on ElasticSearch? 

I noticed high disk usage on my self-host installation, and wanted to reset all my data, but saw that ElasticSearch still used a lot of disk space. I just removed the indexes manually which cleared many GBs. 

Maybe Exceptionless should remove those indices as part of the "reset project data" feature.

**Comment by niemyjski** [comment]
No, it shouldn't drop indices because there should be other projects in the index and we don't really know that. We could query but it would only be valid case if you only ever had one project which would probably be a very very small percentage of the time. Maintain indexes will drop indexes based on max retention period setting (or should). If you want to remove an index, it's best to drop it via elasticsearch directly.

**Comment by niemyjski** [comment]
Thanks for the feedback, I've updated my previous response (not sure if you'll see it via email only).

**Comment by qwertio** [comment]
My use case is only for one project, so I guess that's why it made sense to
me (even though I'm not very familiar with ElasticSearch).
Thanks for the response and the help, and the project is really amazing.
