### ISSUE TITLE
Are there plans to release a new version?

### ISSUE THREAD

**Issue by MetSystem** [exceptionless/Exceptionless#432]
Are there plans to release a new version?

**Comment by niemyjski** [comment]
Yes, we've been letting it bake a long while and working on our k8s infrastructure. We do need to get a release out. You can use our official ci docker images to run and deploy the latest images.

**Comment by niemyjski** [comment]
Yes, we are still running into issues with docker-compose which we want to have the default experience. We realize it's been a long time since a release and we want to get it out there but we want to make sure it's rock solid and a great experience. If you could run the latest bits and give us your feedback by following the instructions that would be a huge help.

**Comment by niemyjski** [comment]
I just wanted to let you know we just pushed a new major version :) https://github.com/exceptionless/Exceptionless/releases/tag/v5.0.0
