### ISSUE TITLE
Self-contained docker image for easier self-hosting

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless#638]
Create a docker image that has the entire Exceptionless app in an easy to use single docker container where users can just do a single `docker run` command.

- [x] Start from Elasticsearch base image
- [x] Install dotnet
- [x] Add files from API docker image
- [x] Figure out how to run both Elasticsearch and the aspnet web app at the same time and monitor both processes
- [x] Add files from UI docker image
- [x] Ability to configure UI through environment variables
- [x] Figure out how to host the API and UI in the same ASPNETCORE app
- [x] Figure out how to enable SPA mode (push state)
- [x] Figure out how to map a volume for ES data so that it persists between runs
- [x] Figure out how to use an SSL certificate and run in HTTPS required mode
- [x] Figure out how to enable email sending
- [x] Publish docker images to Docker hub
- [x] Update self-hosting documentation

**Comment by gmbzero** [comment]
How to use, how to write command?

**Comment by ejsmith** [comment]
@gmbzero I still need to update the self-hosting docs, but I did update the README in the project to show how to run a simpler simple testing instance and then there is also this [hosting samples file](https://github.com/exceptionless/Exceptionless/blob/master/samples/hosting-samples.sh) that shows how to run it at different levels.

**Comment by Phyxion** [comment]
> 
> 
> @gmbzero I still need to update the self-hosting docs, but I did update the README in the project to show how to run a simpler simple testing instance and then there is also this [hosting samples file](https://github.com/exceptionless/Exceptionless/blob/master/samples/hosting-samples.sh) that shows how to run it at different levels.

Been trying it out locally, this command works for me (Exceptionless logs everything):
docker run --rm -it -p 5000:80 exceptionless/exceptionless

However, the [docker-compose](https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml) file doesn't work for me. I initially had redis removed, but then it immediately crashes. After re-enabling it I managed to create a new account, organization and project, but nothing gets logged to it. I've tried to recreate it a couple of times (from scratch), but the result remains the same.

**Comment by niemyjski** [comment]
What errors do you get / what do your logs look like when it crashes?

**Comment by Phyxion** [comment]
The errors are only if I remove all redis stuff from the docker-compose file. I think it was a null reference exception, but I'll try to recreate it again. It didn't log anything with redis enabled (if that was unclear).

**Comment by Phyxion** [comment]
Hm, it no longer throws an exception anymore, that's odd. I have just recreated it from scratch again. What's still broken though is that nothing gets logged (with or without redis). 

**We haven't received any data!**

**Comment by ejsmith** [comment]
Wondering if you are ending up using old docker images that you have cached locally. I just updated the [docker-compose.yml](https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml) file to have explicit image versions in it. Can you try that?

**Comment by Phyxion** [comment]
I've not dockered (?) Exceptionless before, so that shouldn't be the case. With the previous docker compose file these versions were already installed. I'll do another sweep tomorrow.

**Comment by ejsmith** [comment]
I just reset everything locally and made sure I was completely clean and just do docker-compose up on that [docker-compose.yml](https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml) file and the app came up and worked as expected.

**Comment by Phyxion** [comment]
> I just reset everything locally and made sure I was completely clean and just do docker-compose up on that [docker-compose.yml](https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml) file and the app came up and worked as expected.

It also logs stuff for you? That's odd. I am enable to sign in and create projects etc, but no events are logged. I'll give it another try tomorrow.

**Comment by Phyxion** [comment]
It seems some stuff was left from my initial version without redis. I've now purged all data and volumes and have found this out:
- With everything initially enabled, it's logging correctly.
- If redis is disabled (or disabled initially), it won't log anything.

**Comment by ejsmith** [comment]
That docker-compose setup requires Redis because the jobs are running out of process and the app is using Redis for queues.

**Comment by ejsmith** [comment]
Not sure what you are trying to accomplish, but the app can be setup in a variety of ways. Why are you trying to disable Redis?

**Comment by Phyxion** [comment]
I never had redis installed with the non-docker version so I thought I might as well not use it here either. I already tried to change EX_RunJobsInProcess to true (as I had before) but that didn't work either. Regardless, with redis is fine too. It doesn't matter me too much.

**Comment by ejsmith** [comment]
There are other simpler setups now. Are you aware of those? Take a look at [hosting-samples.sh](https://github.com/exceptionless/Exceptionless/blob/master/samples/hosting-samples.sh). We have a single docker image that contains Elasticsearch, the API and the UI and runs jobs in process. You can run that as simple as `docker run --rm -it -p 5000:80 -v ~/esdata:/usr/share/elasticsearch/data exceptionless/exceptionless:6.1.0` which runs the app and maps a data volume to your local computer so that data is persisted if the docker image is restarted. That is the absolute simplest way to run Exceptionless if you don't have a lot of data and it's not critical.

**Comment by Phyxion** [comment]
Yeah, I've seen (and tried) that one, but wasn't sure what was included in that image so I opted for the compose file. I hope to migrate Exceptionless to docker, but I'm wondering what the best way is to run the DataMigration job, I'm not seeing much on the doc page on how you'd normally run those.

**Comment by Phyxion** [comment]
I managed to run the migration. As it might be of use to some, here are the steps:
- Add your existing Elasticsearch instance to reindex.remote.whitelist in the ES docker instance and restart it.
- (Depending on your configuration) Set existing ES's host to 0.0.0.0, otherwise the Job won't be able to connect to it. Restart it.
- Set ASPNETCORE_URLS environment variable of the Jobs instance to another port (as another instance is already running).
- Make sure to point EX_ConnectionStrings__ElasticsearchToMigrate to your existing ES instance, and not EX__ElasticsearchToMigrate.
- Execute **dotnet Exceptionless.Job.dll DataMigration**.

That said, after processing events longer ago than about a month the migrations started throwing exceptions for me.

[11:16:09 ERR] Error creating the index prod-events-v1-2020.05.01: Original: (503 - ElasticsearchClientException) Request failed to execute. Call: Status code 503 from: PUT /prod-events-v1-2020.05.01. ServerError: Type: process_cluster_event_timeout_exception Reason: "failed to process cluster event (create-index [prod-events-v1-2020.05.01], cause [api]) within 30s"
Server: (503) Type: process_cluster_event_timeout_exception Reason: "failed to process cluster event (create-index [prod-events-v1-2020.05.01], cause [api]) within 30s"

This goes on and on, not entirely sure what's causing it. Both ES instances are still working and accessible. I can restart migration and then a couple more are usually done, but as it starts from scratch, this doesn't seem like the best way, and it'll eventually have the same errors again. I might just use two instances for a while and see how that goes.

**Comment by ejsmith** [comment]
@Phyxion I'm going to close this issue. If you are still having a migration issue then can you please open a new issue for that?
