### ISSUE TITLE
405 Error when i am login

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#674]
![图片](https://user-images.githubusercontent.com/30283517/87911647-9021d000-ca9e-11ea-95b4-ca47b9b6cba8.png)
my yml file is here
[docker-compose.zip](https://github.com/exceptionless/Exceptionless/files/4946175/docker-compose.zip)
the version is 6.0.0 
i just download it , and modify some port and docker-compose up -d
it like a nginx error
im try to change HttpMethod POST to Get，it works! but can not open the mainpage。
im try to change nginx conf file,but i can`t   find it

**Comment by XLJ-CN** [comment]
sorry for my poor English

**Comment by niemyjski** [comment]
Hello, this is due to the docker-compose file you are using doesn't have the server api image running. Please use the following  docker-compose file (https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml) or use our new single docker image you can run as simple as this `docker run --rm -it -p 5000:80 exceptionless/exceptionless:6.1.0`

**Comment by XLJ-CN** [comment]
thank you  sir   ,it works
