### ISSUE TITLE
The long  log text was truncated,and can not break line .

### ISSUE THREAD

**Issue by XLJ-CN** [exceptionless/Exceptionless#749]
![图片](https://user-images.githubusercontent.com/30283517/96398719-1c0ed980-11ff-11eb-871e-883d91b4657a.png)
As you can see，i save a long log, but it was truncated.
And , i try many ways to break line, as \r\n  <br>  ，it can not work……
thank you sir, and hope response.

**Comment by niemyjski** [comment]
This is by design. You'll need to copy the event json to look at the full stack trace stored inside of a log message. We truncate and strip line feeds from the messages (client side) so extremely long content doesn't take up the whole screen. We recommend sending errors instead of log messages with the stack trace as this provides multiple benefits. Please let us know if you have any questions.

**Comment by XLJ-CN** [comment]
thank you sir 
good design!
