### ISSUE TITLE
Unable To Find Exceptionless.Job.dll To Run Migration

### ISSUE THREAD

**Issue by LydellM** [exceptionless/Exceptionless#766]
In the [upgrading from v6 to v7 documentation](https://github.com/exceptionless/Exceptionless/wiki/Upgrading#upgrading-from-v6-to-v7), it has a line about migrating data. I am unable to run that in the latest docker container as I can't find Exceptionless.Job.dll anywhere. 

I tried running this command (`docker container exec exceptionless_app dotnet Exceptionless.Job.dll Migration`) but it fails with this error (`Could not execute because the specified command or file was not found.`) I used this command (`docker exec -it exceptionless_app bash`) to get a shell into the container and ran `ls` to get a list of files, but there isn't any Exceptionless.Job.dll file.

Where is this file or how can I run migrations so I can use the latest version of Exceptionless? Let me know if you need any info from me. Thanks!

**Comment by niemyjski** [comment]
You need to use the job image and pass the Migration as an arg. The Api docker container does not contain the jobs executable. Please let us know if you have any questions and please feel free to suggest any changes for the docs.

**Comment by LydellM** [comment]
Are there any examples of this that I can use to get started?

**Comment by niemyjski** [comment]
You can run it via `docker run exceptionless/job:latest migration` or by passing `migration` as an argument in your docker-compose file.

**Comment by LydellM** [comment]
I must still be doing something wrong. See below for the command I am using to start Exceptionless and the command to run the migration job. I removed some sensitive data including the SSL cert info and the email connection string from the Exceptionless command.

Command to start Exceptionless:
`docker run -d --name exceptionless_app -it -p 80:80 -p 443:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=443 -v /exceptionless/esdata:/usr/share/elasticsearch/data exceptionless/exceptionless:latest`

Command to run migration:
`docker run exceptionless/job:latest migration`

The migration job just keeps giving the below message after it starts.  

`[14:39:43 INF] Waiting for startup actions to be completed for 00:40...
[14:39:44 ERR] Health check Elasticsearch completed after 1.7024ms with status Unhealthy and description 'null'
[14:39:45 ERR] Health check Elasticsearch completed after 1.8531ms with status Unhealthy and description 'null'
[14:39:46 ERR] Health check Elasticsearch completed after 1.4862ms with status Unhealthy and description 'null'
[14:39:47 ERR] Health check Elasticsearch completed after 1.5208ms with status Unhealthy and description 'null'
[14:39:48 ERR] Health check Elasticsearch completed after 2.2311ms with status Unhealthy and description 'null'
[14:39:48 INF] Waiting for startup actions to be completed for 00:45...
`
I'm guessing the issue is that I left the Elasticsearch connection string out of the migration command, but I'm not sure what that needs to be as I'm not very familiar with Elasticsearch

**Comment by niemyjski** [comment]
The `exceptionless/exceptionless:latest` container exposes port 80 as well as Elasticsearch on port 9200. I think you just need to expose port 9200 (`-p 9200:9200`) and it should work. It's failing because it cannot talk to Elasticsearch. If you can run `curl http://localhost:9200` you are good. If not, you'll need to also figure out the host name and update the Elasticsearch connection string you pass to the jobs docker container. Would you mind posting your final solution so we can update the docs for this. Our apologies for this being a little rough, we do all our migration testing via local ide and then via helm/k8s.

**Comment by ejsmith** [comment]
It does not need port 9200 exposed outside of docker. Elasticsearch runs inside of the same image. It's an all in one image. I see on the command that you are using to run the migration though, you are using the job image which does not run elasticsearch internally and you aren't attaching the elasticsearch volume which means that it's not going to be able to access your data. We make the all in one image as a simple way to run Exceptionless, but we haven't tested upgrading or running migrations on it since it's really meant for use cases like just quickly trying the app out as well as when you are ok with potential data loss since there aren't any backups being run or anything like that.  That being said, I would like this scenario to work. I think the problem is that the all in one image starts build ES and Exceptionless in background services. So we need some way of triggering the migration job to run. Looking at the way it's currently setup it doesn't look like it's possible. I think I can make some changes to make it a lot easier. I think the only option right now is to run the app how you are currently running it, but also expose port 9200 to give access to elasticsearch from outside of that container and then run the migration job in a different container and point it's elasticsearch configuration at that container (which actually might be the default config since it should be pointed to localhost 9200 by default.

**Comment by ejsmith** [comment]
I was kind of rambling in that last message. Basically, it's possibly currently, but probably not easy to upgrade major versions. I will work on making it possible to run the migration job using the all in one container.

**Comment by LydellM** [comment]
Thanks for taking the time to help me here! I exposed port 9200 and was able to run `curl http://localhost:9200` but the migration still didn't run and gave the same error as above. 

We do have backups of our server, so we will restore the backups and continue using version 6 for now. I feel like most of the issue here is my general lack of knowledge about docker and Elasticsearch. I mostly do desktop development so I'm just not as familiar with web development technologies as I should be. 

You can close this issue if you want as I feel it will probably get resolved when issue #745 is complete. Thanks again for giving me ideas on what to try!

**Comment by ejsmith** [comment]
Thanks @LydellM. Sorry the answer isn't better at the moment. I want to make this much easier for self-hosters.

**Comment by niemyjski** [comment]
We've greatly improved this in 7.1 by allowing you to run a migration as simply as `docker run --rm -it exceptionless/exceptionless:latest DataMigration`
