### ISSUE TITLE
Should error events appear as exceptions?

### ISSUE THREAD

**Issue by strombringer** [exceptionless/Exceptionless#79]
I'm trying out the v2 API and would like to register exceptions without using one of the existing clients. From what I read in the documentation I thought I could use the /api/v{version}/projects/{projectId}/events endpoint and simply send an event like in the example:

```javascript
{ "type": "error", "source": "Test", "date": "2013-10-16T18:59:09.579Z","@error": { "message": "Simple Exception","type": "System.Exception","stack_trace": " at Client.Tests.ExceptionlessClientTests.CanSubmitSimpleException() in c:\Code\Exceptionless\Source\Clients\Tests\ExceptionlessClientTests.cs:line 77"}}
```

I tried @error and @simple_error and the event appears in the event log, but not in the exceptions dashboard. What do I have to do in order to register exceptions?

**Comment by niemyjski** [comment]
Yes, that will work. 

```JSON
{  
   "type":"error",
   "source":"Test",
   "@simple_error":{  
      "message":"Simple Exception",
      "type":"System.Exception",
      "stack_trace":" at Client.Tests.ExceptionlessClientTests.CanSubmitSimpleException() in c:\\Code\\Exceptionless\\Source\\Clients\\Tests\\ExceptionlessClientTests.cs:line 77"
   }
}
```

First there are two things wrong with that example and I've updated our docs. 
1. The date cannot be outside of your retention period, otherwise it's discarded. I'd recommend not even setting it unless you set it to the current time that the error was created.
2. The path wasn't escaped right in json and as such couldn't be deserialized.

If you are not breaking down an exception's stack trace into our Stack Trace model then you must use simple_error as it's handled differently. I'd recommend using one of our clients and submitting an exception and then using the api docs to retrieve the error event to take a look. 

If you have any questions, please let us know. We are here to help.

**Comment by strombringer** [comment]
Great, this works! Thank you
