### ISSUE TITLE
Exception duplicate notification

### ISSUE THREAD

**Issue by knowyi** [exceptionless/Exceptionless#821]
I want multiple events in the same exception to be notified repeatedly. For example, notifications don't repeat in five minutes, or every exception is notified by email. I don't know if I support it at present

**Comment by niemyjski** [comment]
We currently have no plans to send duplicates within a short timeframe, but we would like to have exception rate notifications. We don't want email turning into a bottomless pit that you just start to ignore (because I've ignored some of mine already with our current settings). If you want to see them at a higher rate, we recommend marking an event as critical which will allow it to be sent more often. Does this help? Would rate based exception notifications work for you?

**Comment by knowyi** [comment]
> We currently have no plans to send duplicates within a short timeframe, but we would like to have exception rate notifications. We don't want email turning into a bottomless pit that you just start to ignore (because I've ignored some of mine already with our current settings). If you want to see them at a higher rate, we recommend marking an event as critical which will allow it to be sent more often. Does this help? Would rate based exception notifications work for you? Or am I missing a use case here?

At present, I have marked events as key events, and each event needs to be set up, which is a bit cumbersome

**Comment by niemyjski** [comment]
Any recommendations on how we can improve this? Are you marking all of your events as critical? Is there any specific reason for seeing repeat events in an email vs a rate based one?

**Comment by knowyi** [comment]
> Any recommendations on how we can improve this? Are you marking all of your events as critical? Is there any specific reason for seeing repeat events in an email vs a rate based one?

At present  all exceptions are set as key events, because I want to use exceptionless as a log center and an alarm platform for system exceptions. If the interval is too long, developers may not pay enough attention to it
