### ISSUE TITLE
More configuration options for notifications

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless#92]
- Time when the daily project summary should be send
- Quiet hours
- Quiet days (weekend)

It should also be possible to configure the above on organization level, with option to overwrite on selected projects.

Option to get a daily summary on organization level instead for one mail per project.

**Comment by niemyjski** [comment]
Currently emails are sent out at 8/9am in your local time zone. The issue is everyones timezone is different on a project and as such you could get them at different times.

How do you see quiet hours working? What should happen to the notifications if you are in quiet time? Most phones / inboxes already keep quiet when receiving email.

**Comment by KasperLK** [comment]
You're right. Quiet hours is probably most a luxury that can be handled in other ways.
One way of handelig it could be to send an email with a summary of the events that occurred during the quiet hours. Kind of like the daily summart, but just for that period.

**Comment by niemyjski** [comment]
Merging into https://github.com/exceptionless/Exceptionless/issues/69
