### ISSUE TITLE
Set the current version when marking the stack as fixed.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless#96]
To support this we would just need to 
* get the latest version info from elastic and set it in the [stack controller]( https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/StackController.cs#L94)
* Update the [CheckForRegressions](https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Pipeline/030_CheckForRegressionAction.cs) pipeline method to look at the events version and compare it to the stacks fixed in version.

**Comment by ejsmith** [comment]
I want a dialog to be shown that lets you pick the version the stack was fixed in. It would have the following options:
- Current Version (we would get the current version and show it)
- Next Release (we would put some sort of special marker on it that says the next time we detect a new version, set the fixed version on this stack to that)
- Pick a version. (Maybe the fix isn't scheduled to go out yet and won't go out in the next deployment)

**Comment by HankDitko** [comment]
I'd like to add my interest to this request. It would be very convenient to not get stacks marked as Regressed when they show up in older versions.

**Comment by niemyjski** [comment]
I'm adding this to the 4.0 release. I'd like to do it even sooner as it would really help out in other areas. If your willing to take a shot at this in a pull request that would be greatly appreciated.

**Comment by markusgud** [comment]
I very much agree with @HankDitko. It would be nice to not get stacks marked as Regressed when they show up in older versions. We have our software installed in different versions with different clients, so it would be very helpful to only get the Regression status on the exception when it makes sence. Version can be determined from the assembly version of course.

**Comment by BillHenning** [comment]
This is a great idea.

**Comment by boydpatterson** [comment]
I like @ejsmith idea of also setting the version it was fixed in.  Some users are slow to upgrade and could be multiple versions behind.  Consider a bug that is present in v1 and v2.  Customer A is running old v1 and is the first to report the exception.  I mark it as fixed, and that fix will be in next release which is v3.  Customer B is running v2 and hits the same exception for the first time.  It's a newer version than the one where it was originally marked as fixed, but should not be considered regressed since it's still earlier than the version actually containing the fix.

At a minimum, don't consider it regressed if the version of the exception matches a previous exception where it was marked as fixed.  I can always mark it fixed again if reported in subsequent versions and, eventually, have all the offending versions marked as fixed.

Ideally, setting the fixed version in the beginning will save that extra work and reduce the "noise" of exceptions that do not require attention.

**Comment by srijken** [comment]
Also consider versions, apart from having one version. We could do a hotfix 1.2.0 -> 1.2.1 and 2.3.2 -> 2.3.3. In that case you have multiple "current" versions

**Comment by ejsmith** [comment]
I definitely want this feature as well. My only concern is how to keep it simple to mark things fixed. Don't really want to force the user to manually enter a version number. We can auto populate a list, but that list could get huge and we the version that it's fixed in might not even be released yet so you wouldn't even be able to list the correct version.

**Comment by niemyjski** [comment]
Well, we could query for all the versions and pick the latest stable one that the error occurred on and set as the one where the exception occurred in. then any future stable version (no version suffix) we reopen it).

**Comment by niemyjski** [comment]
@sander wouldn't you have different projects for multiple different versions? I'd like to keep it simple with one version but we do have our spa app and server app in the same project

**Comment by niemyjski** [comment]
This is deploying and will be incrementally worked on. We have support for specifying a fixed in version but we don't yet have a public api for listing all the unique versions. That will be coming once we refactor the stats api to support returning complex types.

@srijken right now, were only going to support one fixed in version. So you'd need to pick the highest version.
