### ISSUE TITLE
Docker production config?

### ISSUE THREAD

**Issue by Daniel15** [exceptionless/Exceptionless#964]
The page at https://exceptionless.com/docs/self-hosting/docker/ says that all the Docker examples are "non-production" setups. How do I run Exceptionless via Docker in production?

**Comment by niemyjski** [comment]
We recommend hosting in kubernetes for production: https://exceptionless.com/docs/self-hosting/kubernetes/  We don't really have any guides for running in prod with just docker compose because we don't do that ourselves. I however wouldn't use the all in one image unless your instance size will be small as it runs Elasticsearch and everything else inside of the same container. I'd probably start with https://github.com/exceptionless/Exceptionless/blob/master/samples/docker-compose.yml so you can scale out the jobs by adding additional job instances.

Please let us know if you have any questions.
